FROM node:21.6.1-alpine3.19 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm i
COPY . .
RUN npm run build

FROM nginxinc/nginx-unprivileged:1.25.3

COPY --from=builder /app/build /usr/share/nginx/html/openapi-ui
COPY deploy/ /

USER root
RUN chmod g+rw -R /run /usr/share/nginx/html \
  && chown root:root /usr/share/nginx/html

USER 1001

CMD ["nginx", "-g", "daemon off;"]
