export const BASE_API_GROUP = import.meta.env.VITE_CUSTOMIZATION_API_GROUP
export const BASE_API_VERSION = import.meta.env.VITE_CUSTOMIZATION_API_VERSION
export const BASE_PROJECTS_VERSION = import.meta.env.VITE_PROJECTS_VERSION
export const BASE_PROJECTS_RESOURCE_NAME = import.meta.env.VITE_PROJECTS_RESOURCE_NAME
export const BASE_MARKETPLACE_RESOURCE_NAME = import.meta.env.VITE_MARKETPLACE_RESOURCE_NAME
export const BASE_MARKETPLACE_KIND = import.meta.env.VITE_MARKETPLACE_KIND
export const BASE_INSTANCES_VERSION = import.meta.env.VITE_INSTANCES_VERSION
